name: Data Pipeline Medallion

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Esto permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Actualizado a 3.11 para evitar warnings de deprecación

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Pipeline
        env:
          # Mapeamos los secretos de GitHub a variables de entorno que Python puede leer
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python -m src.main
