name: Data Pipeline Medallion

on:
  # 1. Ejecución automática diaria (00:00 hora Argentina / 03:00 UTC)
  schedule:
    - cron: '0 3 * * *' 
  
  # 2. Permite ejecución manual desde la pestaña Actions
  workflow_dispatch: 
    inputs:
      tipo_carga:
        description: 'Selecciona el tipo de carga'
        required: true
        default: 'INCREMENTAL'
        type: choice
        options:
          - GLOBAL
          - INCREMENTAL

# NOTA: Se eliminó el bloque 'push' para evitar ejecuciones automáticas al subir código.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir --upgrade -r requirements.txt kagglesdk

      - name: Ejecutar Pipeline Completo (Bronze + Silver)
        env:
          # Credenciales para Storage (Bronze)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # Token para Kaggle
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_CONFIG_DIR }}
          # Variables de control
          TIPO_CARGA: ${{ github.event.inputs.tipo_carga || 'INCREMENTAL' }}
          # Credenciales para SQL (Silver)
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          python -m src.main
